# Generated by Django 5.2.8 on 2025-11-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('unit', models.CharField(default='м²', max_length=200, verbose_name='Единица  измерения')),
                ('category', models.CharField(choices=[('construction', 'Строительство'), ('repair', 'Ремонт'), ('design', 'Дизайн'), ('enginering', 'Инженерия'), ('other', 'Другие виды услуг')], max_length=100, verbose_name='Категория')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Сроки выполнения')),
                ('is_aviable', models.BooleanField(default=True, verbose_name='Доступность услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['category', 'name'],
            },
        ),
    ]
