# Generated by Django 5.2.8 on 2025-11-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroycom_web', '0002_alter_services_is_aviable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='is_aviable',
            field=models.TextField(max_length=100, verbose_name='Доступность услуги'),
        ),
    ]
